/*
  File autogenerated by gengetopt version 2.22.5
  generated with the following command:
  gengetopt -u

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "DAFS: dual decomposition for simultaneous aligning and folding RNA sequences.";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_full_help[] = {
  "  -h, --help                 Print help and exit",
  "      --full-help            Print help, including hidden options, and exit",
  "  -V, --version              Print version and exit",
  "  -r, --refinement=INT       The number of iteration of the iterative refinment \n                                (default=`0')",
  "  -w, --weight=FLOAT         Weight of the expected accuracy score for \n                               secondary structures  (default=`4.0')",
  "      --eta=FLOAT            Initial step width for the subgradient \n                               optimization  (default=`0.5')",
  "  -m, --max-iter=INT         The maximum number of iteration of the subgradient \n                               optimization  (default=`600')",
  "  -f, --fourway-pct=FLOAT    Weight of four-way PCT  (default=`0.0')",
  "  -v, --verbose=INT          The level of verbose outputs  (default=`0')",
  "\nOptions for alignments:",
  "  -a, --align-model=STRING   Alignment model for calcualating matching \n                               probablities  (possible values=\"CONTRAlign\", \n                               \"ProbCons\" default=`ProbCons')",
  "  -p, --align-pct=FLOAT      Weight of PCT for matching probabilities  \n                               (default=`0.25')",
  "  -u, --align-th=FLOAT       Threshold for matching probabilities  \n                               (default=`0.01')",
  "      --align-aux=FILENAME   Load matching probability matrices from FILENAME",
  "\nOptions for folding:",
  "  -s, --fold-model=STRING    Folding model for calculating base-pairing \n                               probablities  (possible values=\"Boltzmann\", \n                               \"Vienna\", \"CONTRAfold\" default=`Boltzmann')",
  "      --fold-decoder=STRING  Decoder for common secondary structure prediction  \n                               (possible values=\"Nussinov\", \"IPknot\" \n                               default=`Nussinov')",
  "  -q, --fold-pct=FLOAT       Weight of PCT for base-pairing probabilities  \n                               (default=`0.25')",
  "  -t, --fold-th=FLOAT        Threshold for base-pairing probabilities  \n                               (default=`0.2')",
  "  -g, --gamma=FLOAT          Specify the threshold for base-pairing \n                               probabilities by 1/(gamma+1))",
  "      --no-alifold           No use of RNAalifold for calculating base-pairing \n                               probabilities  (default=off)",
  "  -T, --fold-th1=FLOAT       Threshold for base-pairing probabilities of the \n                               conclusive common secondary structures",
  "  -G, --gamma1=FLOAT         Specify the threshold for base-pairing \n                               probabilities of the conclusive common secondary \n                               structuresby 1/(gamma+1))",
  "      --ipknot               Set optimized parameters for IPknot decoding \n                               (--fold-decoder=IPknot -g4,8 -G2,4 --bp-update1) \n                                (default=off)",
  "      --bp-update            Use the iterative update of BPs  (default=off)",
  "      --bp-update1           Use the iterative update of BPs for the final \n                               prediction  (default=off)",
  "      --fold-aux=FILENAME    Load base-pairing probability matrices from \n                               FILENAME",
    0
};

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_full_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_full_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_full_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_full_help[4];
  gengetopt_args_info_help[4] = gengetopt_args_info_full_help[6];
  gengetopt_args_info_help[5] = gengetopt_args_info_full_help[8];
  gengetopt_args_info_help[6] = gengetopt_args_info_full_help[9];
  gengetopt_args_info_help[7] = gengetopt_args_info_full_help[10];
  gengetopt_args_info_help[8] = gengetopt_args_info_full_help[12];
  gengetopt_args_info_help[9] = gengetopt_args_info_full_help[14];
  gengetopt_args_info_help[10] = gengetopt_args_info_full_help[15];
  gengetopt_args_info_help[11] = gengetopt_args_info_full_help[18];
  gengetopt_args_info_help[12] = gengetopt_args_info_full_help[21];
  gengetopt_args_info_help[13] = gengetopt_args_info_full_help[23];
  gengetopt_args_info_help[14] = 0; 
  
}

const char *gengetopt_args_info_help[15];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);

static int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error);

const char *cmdline_parser_align_model_values[] = {"CONTRAlign", "ProbCons", 0}; /*< Possible values for align-model. */
const char *cmdline_parser_fold_model_values[] = {"Boltzmann", "Vienna", "CONTRAfold", 0}; /*< Possible values for fold-model. */
const char *cmdline_parser_fold_decoder_values[] = {"Nussinov", "IPknot", 0}; /*< Possible values for fold-decoder. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->refinement_given = 0 ;
  args_info->weight_given = 0 ;
  args_info->eta_given = 0 ;
  args_info->max_iter_given = 0 ;
  args_info->fourway_pct_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->align_model_given = 0 ;
  args_info->align_pct_given = 0 ;
  args_info->align_th_given = 0 ;
  args_info->align_aux_given = 0 ;
  args_info->fold_model_given = 0 ;
  args_info->fold_decoder_given = 0 ;
  args_info->fold_pct_given = 0 ;
  args_info->fold_th_given = 0 ;
  args_info->gamma_given = 0 ;
  args_info->no_alifold_given = 0 ;
  args_info->fold_th1_given = 0 ;
  args_info->gamma1_given = 0 ;
  args_info->ipknot_given = 0 ;
  args_info->bp_update_given = 0 ;
  args_info->bp_update1_given = 0 ;
  args_info->fold_aux_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->refinement_arg = 0;
  args_info->refinement_orig = NULL;
  args_info->weight_arg = 4.0;
  args_info->weight_orig = NULL;
  args_info->eta_arg = 0.5;
  args_info->eta_orig = NULL;
  args_info->max_iter_arg = 600;
  args_info->max_iter_orig = NULL;
  args_info->fourway_pct_arg = 0.0;
  args_info->fourway_pct_orig = NULL;
  args_info->verbose_arg = 0;
  args_info->verbose_orig = NULL;
  args_info->align_model_arg = gengetopt_strdup ("ProbCons");
  args_info->align_model_orig = NULL;
  args_info->align_pct_arg = 0.25;
  args_info->align_pct_orig = NULL;
  args_info->align_th_arg = 0.01;
  args_info->align_th_orig = NULL;
  args_info->align_aux_arg = NULL;
  args_info->align_aux_orig = NULL;
  args_info->fold_model_arg = gengetopt_strdup ("Boltzmann");
  args_info->fold_model_orig = NULL;
  args_info->fold_decoder_arg = gengetopt_strdup ("Nussinov");
  args_info->fold_decoder_orig = NULL;
  args_info->fold_pct_arg = 0.25;
  args_info->fold_pct_orig = NULL;
  args_info->fold_th_arg = NULL;
  args_info->fold_th_orig = NULL;
  args_info->gamma_arg = NULL;
  args_info->gamma_orig = NULL;
  args_info->no_alifold_flag = 0;
  args_info->fold_th1_arg = NULL;
  args_info->fold_th1_orig = NULL;
  args_info->gamma1_arg = NULL;
  args_info->gamma1_orig = NULL;
  args_info->ipknot_flag = 0;
  args_info->bp_update_flag = 0;
  args_info->bp_update1_flag = 0;
  args_info->fold_aux_arg = NULL;
  args_info->fold_aux_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{

  init_help_array(); 
  args_info->help_help = gengetopt_args_info_full_help[0] ;
  args_info->full_help_help = gengetopt_args_info_full_help[1] ;
  args_info->version_help = gengetopt_args_info_full_help[2] ;
  args_info->refinement_help = gengetopt_args_info_full_help[3] ;
  args_info->weight_help = gengetopt_args_info_full_help[4] ;
  args_info->eta_help = gengetopt_args_info_full_help[5] ;
  args_info->max_iter_help = gengetopt_args_info_full_help[6] ;
  args_info->fourway_pct_help = gengetopt_args_info_full_help[7] ;
  args_info->verbose_help = gengetopt_args_info_full_help[8] ;
  args_info->align_model_help = gengetopt_args_info_full_help[10] ;
  args_info->align_pct_help = gengetopt_args_info_full_help[11] ;
  args_info->align_th_help = gengetopt_args_info_full_help[12] ;
  args_info->align_aux_help = gengetopt_args_info_full_help[13] ;
  args_info->fold_model_help = gengetopt_args_info_full_help[15] ;
  args_info->fold_decoder_help = gengetopt_args_info_full_help[16] ;
  args_info->fold_pct_help = gengetopt_args_info_full_help[17] ;
  args_info->fold_th_help = gengetopt_args_info_full_help[18] ;
  args_info->fold_th_min = 0;
  args_info->fold_th_max = 0;
  args_info->gamma_help = gengetopt_args_info_full_help[19] ;
  args_info->gamma_min = 0;
  args_info->gamma_max = 0;
  args_info->no_alifold_help = gengetopt_args_info_full_help[20] ;
  args_info->fold_th1_help = gengetopt_args_info_full_help[21] ;
  args_info->fold_th1_min = 0;
  args_info->fold_th1_max = 0;
  args_info->gamma1_help = gengetopt_args_info_full_help[22] ;
  args_info->gamma1_min = 0;
  args_info->gamma1_max = 0;
  args_info->ipknot_help = gengetopt_args_info_full_help[23] ;
  args_info->bp_update_help = gengetopt_args_info_full_help[24] ;
  args_info->bp_update1_help = gengetopt_args_info_full_help[25] ;
  args_info->fold_aux_help = gengetopt_args_info_full_help[26] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}

/** @brief generic value variable */
union generic_value {
    int int_arg;
    float float_arg;
    char *string_arg;
    const char *default_string_arg;
};

/** @brief holds temporary values for multiple options */
struct generic_list
{
  union generic_value arg;
  char *orig;
  struct generic_list *next;
};

/**
 * @brief add a node at the head of the list 
 */
static void add_node(struct generic_list **list) {
  struct generic_list *new_node = (struct generic_list *) malloc (sizeof (struct generic_list));
  new_node->next = *list;
  *list = new_node;
  new_node->arg.string_arg = 0;
  new_node->orig = 0;
}

/**
 * The passed arg parameter is NOT set to 0 from this function
 */
static void
free_multiple_field(unsigned int len, void *arg, char ***orig)
{
  unsigned int i;
  if (arg) {
    for (i = 0; i < len; ++i)
      {
        free_string_field(&((*orig)[i]));
      }

    free (arg);
    free (*orig);
    *orig = 0;
  }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->refinement_orig));
  free_string_field (&(args_info->weight_orig));
  free_string_field (&(args_info->eta_orig));
  free_string_field (&(args_info->max_iter_orig));
  free_string_field (&(args_info->fourway_pct_orig));
  free_string_field (&(args_info->verbose_orig));
  free_string_field (&(args_info->align_model_arg));
  free_string_field (&(args_info->align_model_orig));
  free_string_field (&(args_info->align_pct_orig));
  free_string_field (&(args_info->align_th_orig));
  free_string_field (&(args_info->align_aux_arg));
  free_string_field (&(args_info->align_aux_orig));
  free_string_field (&(args_info->fold_model_arg));
  free_string_field (&(args_info->fold_model_orig));
  free_string_field (&(args_info->fold_decoder_arg));
  free_string_field (&(args_info->fold_decoder_orig));
  free_string_field (&(args_info->fold_pct_orig));
  free_multiple_field (args_info->fold_th_given, (void *)(args_info->fold_th_arg), &(args_info->fold_th_orig));
  args_info->fold_th_arg = 0;
  free_multiple_field (args_info->gamma_given, (void *)(args_info->gamma_arg), &(args_info->gamma_orig));
  args_info->gamma_arg = 0;
  free_multiple_field (args_info->fold_th1_given, (void *)(args_info->fold_th1_arg), &(args_info->fold_th1_orig));
  args_info->fold_th1_arg = 0;
  free_multiple_field (args_info->gamma1_given, (void *)(args_info->gamma1_arg), &(args_info->gamma1_orig));
  args_info->gamma1_arg = 0;
  free_string_field (&(args_info->fold_aux_arg));
  free_string_field (&(args_info->fold_aux_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}

static void
write_multiple_into_file(FILE *outfile, int len, const char *opt, char **arg, const char *values[])
{
  int i;
  
  for (i = 0; i < len; ++i)
    write_into_file(outfile, opt, (arg ? arg[i] : 0), values);
}

int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->refinement_given)
    write_into_file(outfile, "refinement", args_info->refinement_orig, 0);
  if (args_info->weight_given)
    write_into_file(outfile, "weight", args_info->weight_orig, 0);
  if (args_info->eta_given)
    write_into_file(outfile, "eta", args_info->eta_orig, 0);
  if (args_info->max_iter_given)
    write_into_file(outfile, "max-iter", args_info->max_iter_orig, 0);
  if (args_info->fourway_pct_given)
    write_into_file(outfile, "fourway-pct", args_info->fourway_pct_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", args_info->verbose_orig, 0);
  if (args_info->align_model_given)
    write_into_file(outfile, "align-model", args_info->align_model_orig, cmdline_parser_align_model_values);
  if (args_info->align_pct_given)
    write_into_file(outfile, "align-pct", args_info->align_pct_orig, 0);
  if (args_info->align_th_given)
    write_into_file(outfile, "align-th", args_info->align_th_orig, 0);
  if (args_info->align_aux_given)
    write_into_file(outfile, "align-aux", args_info->align_aux_orig, 0);
  if (args_info->fold_model_given)
    write_into_file(outfile, "fold-model", args_info->fold_model_orig, cmdline_parser_fold_model_values);
  if (args_info->fold_decoder_given)
    write_into_file(outfile, "fold-decoder", args_info->fold_decoder_orig, cmdline_parser_fold_decoder_values);
  if (args_info->fold_pct_given)
    write_into_file(outfile, "fold-pct", args_info->fold_pct_orig, 0);
  write_multiple_into_file(outfile, args_info->fold_th_given, "fold-th", args_info->fold_th_orig, 0);
  write_multiple_into_file(outfile, args_info->gamma_given, "gamma", args_info->gamma_orig, 0);
  if (args_info->no_alifold_given)
    write_into_file(outfile, "no-alifold", 0, 0 );
  write_multiple_into_file(outfile, args_info->fold_th1_given, "fold-th1", args_info->fold_th1_orig, 0);
  write_multiple_into_file(outfile, args_info->gamma1_given, "gamma1", args_info->gamma1_orig, 0);
  if (args_info->ipknot_given)
    write_into_file(outfile, "ipknot", 0, 0 );
  if (args_info->bp_update_given)
    write_into_file(outfile, "bp-update", 0, 0 );
  if (args_info->bp_update1_given)
    write_into_file(outfile, "bp-update1", 0, 0 );
  if (args_info->fold_aux_given)
    write_into_file(outfile, "fold-aux", args_info->fold_aux_orig, 0);
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

static char *
get_multiple_arg_token(const char *arg)
{
  const char *tok;
  char *ret;
  size_t len, num_of_escape, i, j;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');
  num_of_escape = 0;

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
          ++num_of_escape;
        }
      else
        break;
    }

  if (tok)
    len = (size_t)(tok - arg + 1);
  else
    len = strlen (arg) + 1;

  len -= num_of_escape;

  ret = (char *) malloc (len);

  i = 0;
  j = 0;
  while (arg[i] && (j < len-1))
    {
      if (arg[i] == '\\' && 
	  arg[ i + 1 ] && 
	  arg[ i + 1 ] == ',')
        ++i;

      ret[j++] = arg[i++];
    }

  ret[len-1] = '\0';

  return ret;
}

static const char *
get_multiple_arg_token_next(const char *arg)
{
  const char *tok;

  if (!arg)
    return 0;

  tok = strchr (arg, ',');

  /* make sure it is not escaped */
  while (tok)
    {
      if (*(tok-1) == '\\')
        {
          /* find the next one */
          tok = strchr (tok+1, ',');
        }
      else
        break;
    }

  if (! tok || strlen(tok) == 1)
    return 0;

  return tok+1;
}

static int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc);

int
check_multiple_option_occurrences(const char *prog_name, unsigned int option_given, unsigned int min, unsigned int max, const char *option_desc)
{
  int error = 0;

  if (option_given && (min > 0 || max > 0))
    {
      if (min > 0 && max > 0)
        {
          if (min == max)
            {
              /* specific occurrences */
              if (option_given != (unsigned int) min)
                {
                  fprintf (stderr, "%s: %s option occurrences must be %d\n",
                    prog_name, option_desc, min);
                  error = 1;
                }
            }
          else if (option_given < (unsigned int) min
                || option_given > (unsigned int) max)
            {
              /* range occurrences */
              fprintf (stderr, "%s: %s option occurrences must be between %d and %d\n",
                prog_name, option_desc, min, max);
              error = 1;
            }
        }
      else if (min > 0)
        {
          /* at least check */
          if (option_given < min)
            {
              fprintf (stderr, "%s: %s option occurrences must be at least %d\n",
                prog_name, option_desc, min);
              error = 1;
            }
        }
      else if (max > 0)
        {
          /* at most check */
          if (option_given > max)
            {
              fprintf (stderr, "%s: %s option occurrences must be at most %d\n",
                prog_name, option_desc, max);
              error = 1;
            }
        }
    }
    
  return error;
}
int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  int result = EXIT_SUCCESS;

  if (cmdline_parser_required2(args_info, prog_name, 0) > 0)
    result = EXIT_FAILURE;

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required2 (struct gengetopt_args_info *args_info, const char *prog_name, const char *additional_error)
{
  int error = 0;
  FIX_UNUSED (additional_error);

  /* checks for required options */
  if (check_multiple_option_occurrences(prog_name, args_info->fold_th_given, args_info->fold_th_min, args_info->fold_th_max, "'--fold-th' ('-t')"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->gamma_given, args_info->gamma_min, args_info->gamma_max, "'--gamma' ('-g')"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->fold_th1_given, args_info->fold_th1_min, args_info->fold_th1_max, "'--fold-th1' ('-T')"))
     error = 1;
  
  if (check_multiple_option_occurrences(prog_name, args_info->gamma1_given, args_info->gamma1_min, args_info->gamma1_max, "'--gamma1' ('-G')"))
     error = 1;
  
  
  /* checks for dependences among options */

  return error;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}

/**
 * @brief store information about a multiple option in a temporary list
 * @param list where to (temporarily) store multiple options
 */
static
int update_multiple_arg_temp(struct generic_list **list,
               unsigned int *prev_given, const char *val,
               const char *possible_values[], const char *default_value,
               cmdline_parser_arg_type arg_type,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  /* store single arguments */
  char *multi_token;
  const char *multi_next;

  if (arg_type == ARG_NO) {
    (*prev_given)++;
    return 0; /* OK */
  }

  multi_token = get_multiple_arg_token(val);
  multi_next = get_multiple_arg_token_next (val);

  while (1)
    {
      add_node (list);
      if (update_arg((void *)&((*list)->arg), &((*list)->orig), 0,
          prev_given, multi_token, possible_values, default_value, 
          arg_type, 0, 1, 1, 1, long_opt, short_opt, additional_error)) {
        if (multi_token) free(multi_token);
        return 1; /* failure */
      }

      if (multi_next)
        {
          multi_token = get_multiple_arg_token(multi_next);
          multi_next = get_multiple_arg_token_next (multi_next);
        }
      else
        break;
    }

  return 0; /* OK */
}

/**
 * @brief free the passed list (including possible string argument)
 */
static
void free_list(struct generic_list *list, short string_arg)
{
  if (list) {
    struct generic_list *tmp;
    while (list)
      {
        tmp = list;
        if (string_arg && list->arg.string_arg)
          free (list->arg.string_arg);
        if (list->orig)
          free (list->orig);
        list = list->next;
        free (tmp);
      }
  }
}

/**
 * @brief updates a multiple option starting from the passed list
 */
static
void update_multiple_arg(void *field, char ***orig_field,
               unsigned int field_given, unsigned int prev_given, union generic_value *default_value,
               cmdline_parser_arg_type arg_type,
               struct generic_list *list)
{
  int i;
  struct generic_list *tmp;

  if (prev_given && list) {
    *orig_field = (char **) realloc (*orig_field, (field_given + prev_given) * sizeof (char *));

    switch(arg_type) {
    case ARG_INT:
      *((int **)field) = (int *)realloc (*((int **)field), (field_given + prev_given) * sizeof (int)); break;
    case ARG_FLOAT:
      *((float **)field) = (float *)realloc (*((float **)field), (field_given + prev_given) * sizeof (float)); break;
    case ARG_STRING:
      *((char ***)field) = (char **)realloc (*((char ***)field), (field_given + prev_given) * sizeof (char *)); break;
    default:
      break;
    };
    
    for (i = (prev_given - 1); i >= 0; --i)
      {
        tmp = list;
        
        switch(arg_type) {
        case ARG_INT:
          (*((int **)field))[i + field_given] = tmp->arg.int_arg; break;
        case ARG_FLOAT:
          (*((float **)field))[i + field_given] = tmp->arg.float_arg; break;
        case ARG_STRING:
          (*((char ***)field))[i + field_given] = tmp->arg.string_arg; break;
        default:
          break;
        }        
        (*orig_field) [i + field_given] = list->orig;
        list = list->next;
        free (tmp);
      }
  } else { /* set the default value */
    if (default_value && ! field_given) {
      switch(arg_type) {
      case ARG_INT:
        if (! *((int **)field)) {
          *((int **)field) = (int *)malloc (sizeof (int));
          (*((int **)field))[0] = default_value->int_arg; 
        }
        break;
      case ARG_FLOAT:
        if (! *((float **)field)) {
          *((float **)field) = (float *)malloc (sizeof (float));
          (*((float **)field))[0] = default_value->float_arg;
        }
        break;
      case ARG_STRING:
        if (! *((char ***)field)) {
          *((char ***)field) = (char **)malloc (sizeof (char *));
          (*((char ***)field))[0] = gengetopt_strdup(default_value->string_arg);
        }
        break;
      default: break;
      }
      if (!(*orig_field)) {
        *orig_field = (char **) malloc (sizeof (char *));
        (*orig_field)[0] = 0;
      }
    }
  }
}

int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */
  union generic_value multiple_default_value;

  struct generic_list * fold_th_list = NULL;
  struct generic_list * gamma_list = NULL;
  struct generic_list * fold_th1_list = NULL;
  struct generic_list * gamma1_list = NULL;
  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "refinement",	1, NULL, 'r' },
        { "weight",	1, NULL, 'w' },
        { "eta",	1, NULL, 0 },
        { "max-iter",	1, NULL, 'm' },
        { "fourway-pct",	1, NULL, 'f' },
        { "verbose",	1, NULL, 'v' },
        { "align-model",	1, NULL, 'a' },
        { "align-pct",	1, NULL, 'p' },
        { "align-th",	1, NULL, 'u' },
        { "align-aux",	1, NULL, 0 },
        { "fold-model",	1, NULL, 's' },
        { "fold-decoder",	1, NULL, 0 },
        { "fold-pct",	1, NULL, 'q' },
        { "fold-th",	1, NULL, 't' },
        { "gamma",	1, NULL, 'g' },
        { "no-alifold",	0, NULL, 0 },
        { "fold-th1",	1, NULL, 'T' },
        { "gamma1",	1, NULL, 'G' },
        { "ipknot",	0, NULL, 0 },
        { "bp-update",	0, NULL, 0 },
        { "bp-update1",	0, NULL, 0 },
        { "fold-aux",	1, NULL, 0 },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVr:w:m:f:v:a:p:u:s:q:t:g:T:G:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'r':	/* The number of iteration of the iterative refinment.  */
        
        
          if (update_arg( (void *)&(args_info->refinement_arg), 
               &(args_info->refinement_orig), &(args_info->refinement_given),
              &(local_args_info.refinement_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "refinement", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* Weight of the expected accuracy score for secondary structures.  */
        
        
          if (update_arg( (void *)&(args_info->weight_arg), 
               &(args_info->weight_orig), &(args_info->weight_given),
              &(local_args_info.weight_given), optarg, 0, "4.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "weight", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* The maximum number of iteration of the subgradient optimization.  */
        
        
          if (update_arg( (void *)&(args_info->max_iter_arg), 
               &(args_info->max_iter_orig), &(args_info->max_iter_given),
              &(local_args_info.max_iter_given), optarg, 0, "600", ARG_INT,
              check_ambiguity, override, 0, 0,
              "max-iter", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Weight of four-way PCT.  */
        
        
          if (update_arg( (void *)&(args_info->fourway_pct_arg), 
               &(args_info->fourway_pct_orig), &(args_info->fourway_pct_given),
              &(local_args_info.fourway_pct_given), optarg, 0, "0.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fourway-pct", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* The level of verbose outputs.  */
        
        
          if (update_arg( (void *)&(args_info->verbose_arg), 
               &(args_info->verbose_orig), &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Alignment model for calcualating matching probablities.  */
        
        
          if (update_arg( (void *)&(args_info->align_model_arg), 
               &(args_info->align_model_orig), &(args_info->align_model_given),
              &(local_args_info.align_model_given), optarg, cmdline_parser_align_model_values, "ProbCons", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "align-model", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Weight of PCT for matching probabilities.  */
        
        
          if (update_arg( (void *)&(args_info->align_pct_arg), 
               &(args_info->align_pct_orig), &(args_info->align_pct_given),
              &(local_args_info.align_pct_given), optarg, 0, "0.25", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "align-pct", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* Threshold for matching probabilities.  */
        
        
          if (update_arg( (void *)&(args_info->align_th_arg), 
               &(args_info->align_th_orig), &(args_info->align_th_given),
              &(local_args_info.align_th_given), optarg, 0, "0.01", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "align-th", 'u',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Folding model for calculating base-pairing probablities.  */
        
        
          if (update_arg( (void *)&(args_info->fold_model_arg), 
               &(args_info->fold_model_orig), &(args_info->fold_model_given),
              &(local_args_info.fold_model_given), optarg, cmdline_parser_fold_model_values, "Boltzmann", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "fold-model", 's',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Weight of PCT for base-pairing probabilities.  */
        
        
          if (update_arg( (void *)&(args_info->fold_pct_arg), 
               &(args_info->fold_pct_orig), &(args_info->fold_pct_given),
              &(local_args_info.fold_pct_given), optarg, 0, "0.25", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fold-pct", 'q',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Threshold for base-pairing probabilities.  */
        
          if (update_multiple_arg_temp(&fold_th_list, 
              &(local_args_info.fold_th_given), optarg, 0, "0.2", ARG_FLOAT,
              "fold-th", 't',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Specify the threshold for base-pairing probabilities by 1/(gamma+1)).  */
        
          if (update_multiple_arg_temp(&gamma_list, 
              &(local_args_info.gamma_given), optarg, 0, 0, ARG_FLOAT,
              "gamma", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'T':	/* Threshold for base-pairing probabilities of the conclusive common secondary structures.  */
        
          if (update_multiple_arg_temp(&fold_th1_list, 
              &(local_args_info.fold_th1_given), optarg, 0, 0, ARG_FLOAT,
              "fold-th1", 'T',
              additional_error))
            goto failure;
        
          break;
        case 'G':	/* Specify the threshold for base-pairing probabilities of the conclusive common secondary structuresby 1/(gamma+1)).  */
        
          if (update_multiple_arg_temp(&gamma1_list, 
              &(local_args_info.gamma1_given), optarg, 0, 0, ARG_FLOAT,
              "gamma1", 'G',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            cmdline_parser_print_full_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Initial step width for the subgradient optimization.  */
          if (strcmp (long_options[option_index].name, "eta") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->eta_arg), 
                 &(args_info->eta_orig), &(args_info->eta_given),
                &(local_args_info.eta_given), optarg, 0, "0.5", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "eta", '-',
                additional_error))
              goto failure;
          
          }
          /* Load matching probability matrices from FILENAME.  */
          else if (strcmp (long_options[option_index].name, "align-aux") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->align_aux_arg), 
                 &(args_info->align_aux_orig), &(args_info->align_aux_given),
                &(local_args_info.align_aux_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "align-aux", '-',
                additional_error))
              goto failure;
          
          }
          /* Decoder for common secondary structure prediction.  */
          else if (strcmp (long_options[option_index].name, "fold-decoder") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->fold_decoder_arg), 
                 &(args_info->fold_decoder_orig), &(args_info->fold_decoder_given),
                &(local_args_info.fold_decoder_given), optarg, cmdline_parser_fold_decoder_values, "Nussinov", ARG_STRING,
                check_ambiguity, override, 0, 0,
                "fold-decoder", '-',
                additional_error))
              goto failure;
          
          }
          /* No use of RNAalifold for calculating base-pairing probabilities.  */
          else if (strcmp (long_options[option_index].name, "no-alifold") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->no_alifold_flag), 0, &(args_info->no_alifold_given),
                &(local_args_info.no_alifold_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "no-alifold", '-',
                additional_error))
              goto failure;
          
          }
          /* Set optimized parameters for IPknot decoding (--fold-decoder=IPknot -g4,8 -G2,4 --bp-update1).  */
          else if (strcmp (long_options[option_index].name, "ipknot") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->ipknot_flag), 0, &(args_info->ipknot_given),
                &(local_args_info.ipknot_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "ipknot", '-',
                additional_error))
              goto failure;
          
          }
          /* Use the iterative update of BPs.  */
          else if (strcmp (long_options[option_index].name, "bp-update") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->bp_update_flag), 0, &(args_info->bp_update_given),
                &(local_args_info.bp_update_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "bp-update", '-',
                additional_error))
              goto failure;
          
          }
          /* Use the iterative update of BPs for the final prediction.  */
          else if (strcmp (long_options[option_index].name, "bp-update1") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->bp_update1_flag), 0, &(args_info->bp_update1_given),
                &(local_args_info.bp_update1_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "bp-update1", '-',
                additional_error))
              goto failure;
          
          }
          /* Load base-pairing probability matrices from FILENAME.  */
          else if (strcmp (long_options[option_index].name, "fold-aux") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->fold_aux_arg), 
                 &(args_info->fold_aux_orig), &(args_info->fold_aux_given),
                &(local_args_info.fold_aux_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "fold-aux", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */


  multiple_default_value.float_arg = 0.2;
  update_multiple_arg((void *)&(args_info->fold_th_arg),
    &(args_info->fold_th_orig), args_info->fold_th_given,
    local_args_info.fold_th_given, &multiple_default_value,
    ARG_FLOAT, fold_th_list);
  update_multiple_arg((void *)&(args_info->gamma_arg),
    &(args_info->gamma_orig), args_info->gamma_given,
    local_args_info.gamma_given, 0,
    ARG_FLOAT, gamma_list);
  update_multiple_arg((void *)&(args_info->fold_th1_arg),
    &(args_info->fold_th1_orig), args_info->fold_th1_given,
    local_args_info.fold_th1_given, 0,
    ARG_FLOAT, fold_th1_list);
  update_multiple_arg((void *)&(args_info->gamma1_arg),
    &(args_info->gamma1_orig), args_info->gamma1_given,
    local_args_info.gamma1_given, 0,
    ARG_FLOAT, gamma1_list);

  args_info->fold_th_given += local_args_info.fold_th_given;
  local_args_info.fold_th_given = 0;
  args_info->gamma_given += local_args_info.gamma_given;
  local_args_info.gamma_given = 0;
  args_info->fold_th1_given += local_args_info.fold_th1_given;
  local_args_info.fold_th1_given = 0;
  args_info->gamma1_given += local_args_info.gamma1_given;
  local_args_info.gamma1_given = 0;
  
  if (check_required)
    {
      error += cmdline_parser_required2 (args_info, argv[0], additional_error);
    }

  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  free_list (fold_th_list, 0 );
  free_list (gamma_list, 0 );
  free_list (fold_th1_list, 0 );
  free_list (gamma1_list, 0 );
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
